source 'https://github.com/LeiZong/ZZSpecs.git'
source 'https://github.com/CocoaPods/Specs.git'

use_frameworks!

target 'ZZAuthorKit_Example' do
  pod 'ZZAuthorKit', :path => '../'

  target 'ZZAuthorKit_Tests' do
    inherit! :search_paths

    
  end
end
